### PR TITLE
Make it obvious this is no longer "a thing"

### PR DESCRIPTION
**Pull request by dazoakley**
- Remove all of the remaining code.
- Update the README to only say that this is deprecated and what has
  replaced it.

### CODE REVIEW

**Comment by kenoir** [comment]
Why not delete the repo entirely? Not sure if there is a way to explicitly redirect repos, but might be nice simply to redirect to BBC-News/alephant?

**Comment by samfrench** [comment]
If we ever had to produce a bug fix for a deprecated gem, then it would be handy to have the repo. I know that everything should be upgraded, especially if something is deprecated, but it's highly likely some applications will be using older versions, and may need bug fixing if very little time.

**Comment by samfrench** [comment]
You can redirect repos, but only when renaming. The browser and the API allow these redirects. It doesn't support redirecting to an existing repo.

**Comment by dazoakley** [comment]
Okey doke, i've had a search and there _are_ some apps still using this gem.  So, as a compromise, (following Sams point about bugfixes etc) shall we just merge this PR, and then once the other projects are updated to the newer gems delete the repo?

**Comment by samfrench** [comment]
As the gem is open source, how do we know what is still using it externally, or we just expect them to upgrade?

I guess, the gem will still be available on Rubygems, unless an unpublish happens. Probably not the best thing to do, if it's been available publicly. So deleting the repo should be fine, once we've upgraded our applications.

**Comment by dazoakley** [comment]
Yep, the gem will always be available from rubygems - it's pretty hard to get them to do a permanent removal.  I think we should really expect people to upgrade to the newer gems, you can't support deprecated code indefinitely.

As for the code/repo itself, it's been marked as deprecated since Oct 2014 I think it's reasonable to remove the code and repo once we're done with it.

**Pull request merged**
